config/routes.rb
Rails.application.routes.draw do
  get 'session/new'
  root 'static_pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get     "login"    => "sessions#new"
  post    "login"    => "sessions#create"
  delete  "logout"   => "sessions#destroy"
  get 'users/sign_up' => 'users#new'
  post 'users/sign_up' => 'users#create'
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new;  end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user&.authenticate(params[:session][:password])
      flash[:success] = 'Login success'
      log_in user
      redirect_to user
    else
      flash[:danger] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    log_out if log_in?
    flash[:success] = "You are logged out"
    redirect_to login_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = 'Register successfully'
      redirect_to root_path
    else
      flash[:alert] = 'Register failed'
      render :new
    end
  end

  def show
    @user = User.find_by id: params[:id]
  end

  def user_params
    params.require(:user).permit :email, :name, :password, :password_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete :user_id
  end

  def current_user
    User.find_by(id: session[:user_id])
  end

  def log_in?
    !current_user.nil?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shoppe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  </head>

  <body>
    <section class="content" style="min-height: auto;">
      <% flash.each do |key, value| %>
        <div class="row">
          <div class="alert alert-<%= key %>">
            <%= value %>
          </div>
        </div>
      <% end %>
    </section>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>
<% if log_in? %>
  <label for="">You are logged input <%= current_user.name %></label>
  <%= link_to 'logout', logout_path, method: :delete %>
<% else %>
  <%= link_to 'Register', users_sign_up_path %>
  <%= link_to 'Login',login_path %>
<% end %>

app/views/users/new.html.erb
<div class="container">
  <div class="row">
    <h1 class="title">Register</h1>
  </div>
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <%= form_for :user, url: users_sign_up_path do |f| %>
      <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, placeholder: "Enter your email", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, placeholder: "Enter your name", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, placeholder: "Enter your password", class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation%>
        <%= f.password_field :password_confirmation, placeholder: "Enter your password_confirmation", class: "form-control" %>
      </div>
      <div class="text-center">
        <%= f.submit "register", class: "btn btn-info col-lg-12" %>
      </div>
    <% end %>
  </div>
</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-offset-3 col-lg-6">
      <div class="text-left">
        <label> email: <%= @user.email %></label><br>
        <label> fullname: <%= @user.name %></label><br>
      </div>
      <%= link_to "Logout", logout_path, method: :delete %>
      <%= link_to 'Home', root_path %>
    </div>
  </div>
</div>